Repository acm-ucr/acm-atlas, pull requests merged in 2022-12, with the labels that each got.

#378 Updated README
  README.md
Labels: documentation

#393 Updated discord join link
  components/data/Socials.js
Labels: Footer

#398 Add Winter Project
  components/data/Projects.js
Labels: READY FOR REVIEW

#399 Increased height between elements on mobile
  components/Stats.js
Labels: Home

#401 Spaced out social icons on mobile
  components/Footer.js
Labels: Footer

#403 Add No Upcoming Events text
  components/CalendarEvents.js
Labels: READY FOR REVIEW

#408 Mobile Navbar
  components/Navigation.js
Labels: READY FOR REVIEW

#409 Third Professional Item
  components/Learn.js
Labels: READY FOR REVIEW

#414 Added DS Workshop Series
  components/data/Events.js
  components/data/Filters.js
Labels: Events, READY FOR REVIEW

#422 Enlarged 'No upcoming events' text
  components/CalendarEvents.js
  components/Upcoming.js
Labels: Home

#424 Added CCC discord
  components/Profile.js
  components/StudentOrgs.js
  components/data/Organizations.js
Labels: Join Us

#426 Added discord link for orgs that have them
  components/data/Organizations.js
Labels: Join Us
