Repository acm-ucr/acm-atlas, pull requests merged in 2022-09, with the labels that each got.

#151 Change Navbar Width to 11/12ths
  components/Navigation.js
  package-lock.json
Labels: Home, READY FOR REVIEW

#144 map profile cards
  components/Officers.js
Labels: Board, READY FOR REVIEW

#122 Profile Component
  components/Officers.js
  components/Profile.js
Labels: Board, READY FOR REVIEW

#152 change all fonts to pure black
  components/Filter.js
  components/Gallery.js
  components/Introduction.js
  components/Learn.js
  components/Stats.js
  components/Topic.js
  components/Upcoming.js
  components/Vision.js
  components/What.js
  components/Why.js
Labels: READY FOR REVIEW

#150 Move Custom Toolbar and Event
  components/CalendarEvents.js
  components/CustomEvent.js
  components/CustomToolbar.js
  package-lock.json
Labels: Events, READY FOR REVIEW

#169 stats width
  components/Stats.js
Labels: Home, READY FOR REVIEW

#170 populate stats
  components/Stats.js
Labels: Home, READY FOR REVIEW

#171 faq header
  components/Faq.js
Labels: Join Us, READY FOR REVIEW

#172 update gallery width
  components/Gallery.js
Labels: About Us, READY FOR REVIEW

#175 Rfairooz/topic
  .github/workflows/main.yml
  components/Learn.js
  components/Topic.js
Labels: Home

#176 Rfairooz/landing
  components/Landing.js
  public/keyboard.png
Labels: Home

#168 Update Officer Pictures
  components/Officers.js
  public/cindy.jpg
  public/david.jpg
  public/joshua.jpg
  public/joshua.png
  public/sachin.jpg
Labels: Board, READY FOR REVIEW

#180 Fixed navbar to top, and added bottom border
  components/CalendarEvents.js
  components/Faq.js
  components/Landing.js
  components/Navigation.js
  components/Officers.js
  components/Vision.js
  pages/index.js
Labels: Navigation

#183 clubroom component
  components/Clubroom.js
Labels: Join Us, READY FOR REVIEW

#184 Landing background changed
  components/Landing.js
Labels: Home

#186 Rfairooz/career series
  components/Events.js
Labels: Events

#182 add margins to cramped components
  components/CalendarEvents.js
  components/Faq.js
  components/Introduction.js
  components/Landing.js
  components/Learn.js
  components/Stats.js
  components/StudentOrgs.js
  components/Upcoming.js
Labels: READY FOR REVIEW

#185 Rfairooz/general meetings
  components/Events.js
Labels: Home, Events

#188 Update Initial Main Site
  .github/workflows/main.yml
  components/CalendarEvents.js
  components/Clubroom.js
  components/Events.js
  components/Faq.js
  components/Gallery.js
  components/Introduction.js
  components/Landing.js
  components/Learn.js
  components/Navigation.js
  components/Officers.js
  components/Stats.js
  components/StudentOrgs.js
  components/Topic.js
  components/Upcoming.js
  components/Vision.js
  package.json
  pages/index.js
  public/cindy.jpg
  public/david.jpg
  public/joshua.jpg
  public/joshua.png
  public/keyboard.png
  public/sachin.jpg
Labels: READY FOR REVIEW

#187 Mapping through Student Organizations
  components/Officers.js
  components/Profile.js
  components/StudentOrgs.js
  public/ccc.png
  public/citrushack.png
  public/cutiehack.png
  public/cyberucr.png
  public/designucr.png
  public/gamespawnwhite.jpg
  public/ieee.png
  public/robosub.jpg
  public/rosehack.png
  public/solarcar.png
  public/swe.png
  public/ticsucr.png
  public/uas.png
  public/winc.png
Labels: Join Us, READY FOR REVIEW

#192 add build scripts
  build_dev.sh
  build_main.sh
Labels: READY FOR REVIEW

#190 change names of images with default names
  components/Gallery.js
  components/Vision.js
  components/What.js
  components/Why.js
  public/acm-workshop.jpg
  public/discussion-professors.jpg
  public/discussion-professors2.jpg
  public/discussion-professors3.jpg
  public/discussion.jpg
  public/meeting.png
  public/panel.png
  public/presentation-projects.png
  public/presentation-workflow.png
  public/presentation1.jpg
  public/presentation2.jpg
  public/presentation3.jpg
  public/presentation4.jpg
  public/presentation5.jpg
  public/presentation6.png
  public/presentation7.png
  public/rivera-library.png
Labels: READY FOR REVIEW

#212 increase faq width
  components/Faq.js
Labels: Join Us, READY FOR REVIEW

#214 increase clubroom width & update clubroom text
  components/Clubroom.js
Labels: Join Us, READY FOR REVIEW

#218 Add Favicon
  public/favicon.ico
Labels: Home, READY FOR REVIEW

#220 Logo Size
  components/Introduction.js
  public/meeting.png
Labels: Home, READY FOR REVIEW

#216 Spaced out upcoming events cards, centered upcoming event header, lighten gray on hover (board, student orgs)
  components/CalendarEvents.js
  components/Profile.js
  components/StudentOrgs.js
  components/Upcoming.js
  public/gamespawnwhite.jpg
Labels: Home, Events, READY FOR REVIEW

#189 move static data to separate files
  components/CustomToolbar.js
  components/Faq.js
  components/FaqInfoArray.js
  components/Footer.js
  components/Inspire.js
  components/InspireProjects.js
  components/Officers.js
  components/data/Colors.js
  components/data/Filters.js
  components/data/Officers.js
  components/data/Socials.js
Labels: READY FOR REVIEW

#215 clubroom header
  components/Clubroom.js
Labels: Join Us, READY FOR REVIEW

#225 Navbar resize
  components/Navigation.js
Labels: Navigation, READY FOR REVIEW

#224 Update Main
  .github/workflows/main.yml
  build_dev.sh
  build_main.sh
  components/CalendarEvents.js
  components/Clubroom.js
  components/CustomToolbar.js
  components/Faq.js
  components/FaqInfoArray.js
  components/Footer.js
  components/Inspire.js
  components/InspireProjects.js
  components/Introduction.js
  components/Navigation.js
  components/Officers.js
  components/Profile.js
  components/Stats.js
  components/StudentOrgs.js
  components/Upcoming.js
  components/data/Colors.js
  components/data/Filters.js
  components/data/Officers.js
  components/data/Socials.js
  public/favicon.ico
  public/gamespawnwhite.jpg
  public/meeting.png
Labels: READY FOR REVIEW

#226 Rfairooz/socials calendar
  components/CalendarEvents.js
  components/Clubroom.js
  components/CustomToolbar.js
  components/Event.js
  components/Events.js
  public/pathways.png
  public/resume.jpeg
  public/workshop.jpeg
Labels: READY FOR REVIEW

#229 Center projects header, fix frames component
  components/Inspire.js
  components/Vision.js
  components/What.js
  components/Why.js
Labels: Home, About Us

#241 change clubroom component width from 2/3 to 11/12
  components/Clubroom.js
Labels: READY FOR REVIEW

#230 changed bit/byte events for matching week
  components/Events.js
Labels: Events

#248 remove officer blank fields
  components/data/Officers.js
Labels: READY FOR REVIEW

#263 Fixed Winston Chung Hall Spelling
  components/Clubroom.js
Labels: Join Us

#264 student org ordering
  components/StudentOrgs.js
Labels: Join Us, READY FOR REVIEW

#266 descriptions
  components/Events.js
  package-lock.json
Labels: READY FOR REVIEW

#265 Finish Website 🎉
  .github/dependabot.yaml
  build_dev.sh
  build_main.sh
  components/CalendarEvents.js
  components/Clubroom.js
  components/CustomToolbar.js
  components/Event.js
  components/Events.js
  components/Faq.js
  components/Frame.js
  components/Inspire.js
  components/StudentOrgs.js
  components/Vision.js
  components/What.js
  components/Why.js
  components/data/Officers.js
  package-lock.json
  package.json
  public/pathways.png
  public/resume.jpeg
  public/workshop.jpeg
Labels: READY FOR REVIEW

#268 Metaverse GM description
  components/Events.js
Labels: Events

#282 add tour and picture day
  components/Events.js
Labels: READY FOR REVIEW, Adding an Event

#283 Add new events
  components/Events.js
Labels: READY FOR REVIEW
