Repository acm-ucr/acm-atlas, pull requests merged in 2022-08, with the labels that each got.

#90 create filter component
  .DS_Store
  components/Calendar.js
  components/Filter.js
  package-lock.json
  pages/_document.js
Labels: Events

#88 Sarah rami27/footer
  components/Footer.js
Labels: Footer, READY FOR REVIEW

#95 improve filter data through mapping
  components/Calendar.js
Labels: Events

#100 Rfairooz/learn
  components/Learn.js
  components/Topic.js
Labels: Home, READY FOR REVIEW

#89 stats component
  components/Stats.js
  package-lock.json
  package.json
  pages/_app.js
Labels: Home, READY FOR REVIEW

#106 add project file
  components/Project.js
Labels: Home, READY FOR REVIEW

#101 Rfairooz/topic
  components/Learn.js
  components/Topic.js
Labels: Home, READY FOR REVIEW

#113 add tailwind colors
  tailwind.config.js
Labels: dependencies, READY FOR REVIEW

#87 add calendar button
  .gitignore
  components/Card.js
  components/Event.js
  package-lock.json
  package.json
Labels: Events, READY FOR REVIEW

#108 introduction component
  components/Introduction.js
  public/acm-ucr-logo.png
Labels: Home, READY FOR REVIEW

#117 Footer Mapping
  components/Footer.js
Labels: Footer, READY FOR REVIEW

#115 Responsive navbar
  components/Navigation.js
  package-lock.json
  package.json
Labels: Navigation, DO NOT MERGE

#116 Upcoming Component
  components/Upcoming.js
Labels: Home, READY FOR REVIEW

#94 Working faq component
  components/Faq.js
  package-lock.json
  package.json
  public/chevron.png
  tailwind.config.js
Labels: Join Us, READY FOR REVIEW

#121 Fixed navbar issue
  components/Navigation.js
Labels: Navigation, READY FOR REVIEW

#118 vision component
  components/Vision.js
Labels: About Us, READY FOR REVIEW

#119 what we do component
  components/What.js
Labels: About Us, READY FOR REVIEW

#120 why we do component
  components/Why.js
Labels: About Us, READY FOR REVIEW

#130 change font size - about page
  components/Vision.js
  components/What.js
  components/Why.js
Labels: About Us, READY FOR REVIEW

#128 gallery component
  components/Gallery.js
  pages/about.js
  public/image11.png
  public/image12.png
  public/image13.png
  public/image14.png
  public/image15.png
  public/image16.png
  public/image17.png
Labels: About Us, READY FOR REVIEW

#133 Hover behavior for nav links
  components/Navigation.js
Labels: Navigation, READY FOR REVIEW

#129 Change footer colors
  components/Footer.js
Labels: Footer, READY FOR REVIEW

#132 Fix #98: populate FAQ questions and remove !important from tailwind config
  components/Faq.js
  tailwind.config.js
Labels: Join Us, READY FOR REVIEW

#135 Calendar Component
  components/Calendar.js
  components/CalendarEvents.js
  components/EventInformation.js
  components/Events.js
  components/Navigation.js
  components/PastEvents.js
  package-lock.json
  package.json
  pages/events.js
Labels: Events, READY FOR REVIEW

#140 Added home option to navbar
  components/Navigation.js
Labels: Navigation, READY FOR REVIEW

#142 add answers to FAQ array
  components/Faq.js
Labels: Join Us, READY FOR REVIEW

#141 add CalendarEvents component
  components/CalendarEvents.js
  components/Event.js
  components/EventInformation.js
  components/Events.js
  components/Introduction.js
  components/Navigation.js
  components/Stats.js
  components/Upcoming.js
  package-lock.json
Labels: Events, READY FOR REVIEW

#134 screen width - home page
  components/Learn.js
  components/Stats.js
Labels: Home, READY FOR REVIEW
