Repository acm-ucr/acm-atlas, pull requests merged in 2022-10, with the labels that each got.

#284 Requested Changes
  components/Gallery.js
  components/Introduction.js
  components/Navigation.js
  components/Officers.js
  public/discussion-professors.jpg
  public/rivera-library.png
Labels: READY FOR REVIEW

#290 [#235] optimize bootstrap imports
  components/CalendarEvents.js
  components/Clubroom.js
  components/CustomToolbar.js
  components/Footer.js
  components/Gallery.js
  components/Inspire.js
  components/Introduction.js
  components/Learn.js
  components/Navigation.js
  components/Officers.js
  components/Profile.js
  components/Stats.js
  components/StudentOrgs.js
  components/Upcoming.js
  components/Vision.js
  components/What.js
  components/Why.js
Labels: Home, Events, Join Us, About Us, Board, Navigation, Footer, READY FOR REVIEW

#288 [#242] add boxShadowColor property to Profile
  components/Officers.js
  components/Profile.js
Labels: Join Us, Board, READY FOR REVIEW

#289 [#232] purge the <div> in About component
  components/Vision.js
  pages/about.js
Labels: About Us, READY FOR REVIEW

#294 Add/Fix Events
  components/Events.js
Labels: Adding an Event, Social, General Meeting

#291 Fix Requested Changes
  components/CalendarEvents.js
  components/Clubroom.js
  components/CustomToolbar.js
  components/Events.js
  components/Footer.js
  components/Gallery.js
  components/Inspire.js
  components/Introduction.js
  components/Learn.js
  components/Navigation.js
  components/Officers.js
  components/Profile.js
  components/Stats.js
  components/StudentOrgs.js
  components/Upcoming.js
  components/Vision.js
  components/What.js
  components/Why.js
  pages/about.js
  public/discussion-professors.jpg
  public/rivera-library.png
Labels: READY FOR REVIEW

#295 Fix Movie Night
  components/Events.js
Labels: Social

#286 [#233] move data into /data
  components/CalendarEvents.js
  components/CustomToolbar.js
  components/Faq.js
  components/Footer.js
  components/Inspire.js
  components/Officers.js
  components/StudentOrgs.js
  components/Upcoming.js
  components/data/Board.js
  components/data/Colors.js
  components/data/Events.js
  components/data/Filters.js
  components/data/Organizations.js
  components/data/Projects.js
  components/data/Questions.js
  components/data/Socials.js
Labels: Home, Join Us, READY FOR REVIEW

#297 [#287] separate faq item from faq.js
  components/Faq.js
  components/FaqItem.js
Labels: Join Us, READY FOR REVIEW

#301 [#237] conditionally render icons for board
  components/Profile.js
Labels: Board, READY FOR REVIEW

#300 [#238] conditionally render icons for home
  components/Project.js
Labels: Home, READY FOR REVIEW

#312 [#247] Footer arrangement on mobile
  components/Footer.js
Labels: Footer, READY FOR REVIEW

#314 Nova sagittarii/faq item colors
  components/FaqItem.js
  components/Learn.js
  components/Profile.js
  components/StudentOrgs.js
  components/Topic.js
  components/data/Colors.js
Labels: READY FOR REVIEW

#316 removed unused pictures
  public/discussion-professors2.jpg
  public/discussion-professors3.jpg
  public/linkedin.jpeg
  public/presentation-projects.png
  public/presentation2.jpg
  public/presentation3.jpg
  public/presentation5.jpg
  public/sachin.png
Labels: READY FOR REVIEW

#317 update cyber image
  public/cyberucr.png
Labels: READY FOR REVIEW

#325 Add GM 3 event
  components/data/Events.js
Labels: READY FOR REVIEW

#326 Put GM 3 event in order
  components/data/Events.js
Labels: READY FOR REVIEW

#327 Updated shadow and title color for projects
  components/Inspire.js
  components/Project.js
  components/data/Projects.js
Labels: READY FOR REVIEW

#329 IPad breakpoint fix
  components/CalendarEvents.js
Labels: Events

#331 Added lazy loading for components after landing
  pages/index.js
Labels: READY FOR REVIEW

#332 Lazy Loading in Gallery
  components/Gallery.js
Labels: About Us

#336 Updated colors
  components/data/Projects.js
Labels: READY FOR REVIEW

#337 SEO
  .gitignore
Labels: READY FOR REVIEW

#342 SEO Testing
  .gitignore
  components/Gallery.js
  components/StudentOrgs.js
  components/data/Projects.js
  pages/index.js
Labels: READY FOR REVIEW

#347 Added Mentor/Mentee Event
  components/data/Events.js
Labels: Events, READY FOR REVIEW, Social

#350 Updates
  components/CalendarEvents.js
  components/Gallery.js
  components/Modal.js
  components/data/Events.js
  components/data/Filters.js
  package-lock.json
  package.json
Labels: READY FOR REVIEW

#351 HOTFIX
  components/CalendarEvents.js
  components/Event.js
  components/Filter.js
  components/Modal.js
  components/Upcoming.js
  components/data/Events.js
  components/data/Filters.js
Labels: READY FOR REVIEW
