Repository acm-ucr/acm-atlas, pull requests merged in 2023-03, with the labels that each got.

#567 Created board check presence
  cypress/e2e/board_presence_check.cy.js
Labels: Board, Testing

#566 Created clubroom presence check
  cypress/e2e/clubroom_presence_check.cy.js
Labels: Join Us, Testing

#568 Created Learn Section Presence check
  cypress/e2e/learnSec_pres_check.cy.js
Labels: Home, Testing

#565 Created Project Presence Check
  cypress/e2e/project_presence.cy.js
Labels: Home, Testing

#575 Stats Presence Check
  cypress/e2e/StatsPresenceCheck.cy.js
Labels: Testing

#569 Created What We Do and Image Presence check
  cypress/e2e/Intro_pCheck.cy.js
  cypress/e2e/whatWeDo_pCheck.cy.js
Labels: About Us, Testing

#577 Created Vision Image and Text presence check
  cypress/e2e/board_pCheck.cy.js
  cypress/e2e/clubroom_pCheck.cy.js
  cypress/e2e/learnSec_pCheck.cy.js
  cypress/e2e/projects_pCheck.cy.js
  cypress/e2e/stats_pCheck.cy.js
  cypress/e2e/vision_pCheck.cy.js
Labels: About Us, Testing

#576 Upcoming Events Presence Check
  cypress/e2e/UpcomingEventsPresenceCheck.cy.js
Labels: Testing

#588 Fixed warning when running dev
  components/Navigation.js
  pages/404.js
Labels: Bugfix

#587 Added project event filter
  components/data/Filters.js
Labels: Events
