Repository acm-ucr/acm-atlas, pull requests merged in 2023-06, with the labels that each got.

#673 Kapilan Fix
  components/data/Board.js
  cypress/e2e/board_pCheck.cy.js
Labels: Board

#682 added portal link
  components/data/Projects.js
Labels: Home

#683 added repo
  components/data/Projects.js
Labels: Home

#684 added padding and increased blue bg coverage
  components/Landing.js
  components/Navigation.js
Labels: Home, Bugfix

#691 Login Button Bug Fixed
  components/Navigation.js
  cypress/e2e/navbar_pCheck.cy.js
Labels: Navigation, Bugfix
