Repository acm-ucr/acm-atlas, pull requests merged in 2023-04, with the labels that each got.

#589 google calendar integration for events
  .gitignore
  components/CalendarEvents.js
  components/CustomEvent.js
  components/Modal.js
  components/Upcoming.js
  components/data/Events.js
  components/data/Filters.js
Labels: Home, Events

#590 prod merge for google calendar integration
  .gitignore
  components/CalendarEvents.js
  components/CustomEvent.js
  components/Modal.js
  components/Navigation.js
  components/Upcoming.js
  components/data/Events.js
  components/data/Filters.js
  pages/404.js
Labels: READY FOR REVIEW

#592 Updated Board info
  components/data/Board.js
Labels: Board

#595 Removed Cypress Test Causing PRs To Fail
  cypress/e2e/UpcomingEventsPresenceCheck.cy.js
Labels: Testing

#604 Calendar Presence Check
  cypress/e2e/calendar_pCheck.cy.js
Labels: Testing

#603 Gallery Presence Check
  cypress/e2e/gallery_pCheck.cy.js
  package-lock.json
Labels: Testing

#602 Why We Do It Presence Check
  cypress/e2e/whyWeDo_pCheck.cy.js
Labels: Testing

#606 Changed Medium Link
  components/data/Socials.js
Labels: Footer, Social

#613 Footer Presence Check
  cypress/e2e/footer_pCheck.cy.js
Labels: Testing

#614 Navbar Presence Check
  cypress/e2e/navbar_pCheck.cy.js
Labels: Testing

#612 Changed join faq
  components/data/Questions.js
Labels: Join Us

#616 Upcoming Events Presence Check
  cypress/e2e/upcomingEvents_pCheck.cy.js
Labels: Testing

#622 FAQ Presence Check
  cypress/e2e/faq_pCheck.cy.js
Labels: Testing
