Repository acm-ucr/acm-atlas, pull requests merged in 2023-02, with the labels that each got.

#497 Added roblox workshop
  components/data/Events.js
Labels: Events

#501 Fixed navbar issue
  components/Navigation.js
Labels: Navigation

#505 Modified 404 Page Message
  pages/404.js
Labels: Respository

#506 Removed Null Check and Added Return Statement
  components/Modal.js
Labels: Events

#509 Added privacy workshop
  components/data/Events.js
Labels: Events, Adding an Event

#510 Changed FAQ
  components/data/Questions.js
Labels: Join Us

#514 Made Explicit Comparison
  components/Upcoming.js
Labels: Home, Events

#516 Wrap Link
  components/Modal.js
Labels: Events

#515 Updated DSS workshop
  components/data/Events.js
Labels: Events, Adding an Event, Technical Workshop

#518 Fix Nav + Link
  components/Navigation.js
  components/data/Events.js
Labels: READY FOR REVIEW

#517 next/font implementation
  package-lock.json
  package.json
  pages/_app.js
  tailwind.config.js
Labels: Respository

#519 Update Website
  components/Modal.js
  components/Navigation.js
  components/Upcoming.js
  components/data/Events.js
  package-lock.json
  package.json
  pages/_app.js
  tailwind.config.js
Labels: READY FOR REVIEW

#520 Nav Fixes
  components/Navigation.js
Labels: Navigation, READY FOR REVIEW

#539 Changed DSS/DBS workshop dates
  components/data/Events.js
Labels: Events, Technical Workshop

#540 Add Cypress Testing
  .github/workflows/main.yml
  cypress.config.js
  cypress/component/Home.cy.js
  cypress/e2e/template.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: Testing
