Repository acm-ucr/acm-atlas, pull requests merged in 2025-06, with the labels that each got.

#1124 Andres Lopez / Animated Project Cards
  src/components/events/week/customdayheader.tsx
  src/components/home/featuredprojects.tsx
  src/components/home/projectcard.tsx
Labels: changes requested

#1134 Stat item props
  src/components/hacks/hackathon.tsx
  src/components/home/statsgrid.tsx
  src/components/programs/create/stats.tsx
  src/components/programs/das/stats.tsx
  src/components/programs/forge/stats.tsx
  src/components/programs/spark/stats.tsx
  src/components/statitem.tsx
Labels: approved 1x

#1147 made fixes to stats
  src/components/hacks/aurora/stats.tsx
  src/components/hacks/hackathon.tsx
  src/components/home/statsgrid.tsx
  src/components/programs/create/stats.tsx
  src/components/programs/das/stats.tsx
  src/components/programs/forge/stats.tsx
  src/components/programs/programheader.tsx
  src/components/programs/spark/stats.tsx
Labels: ready for review

#1149 small change
  src/data/hackpacks.tsx
Labels: ready for review

#1130 calendar spacing + link
  package-lock.json
  package.json
  src/components/events/month/calendareventpopover.tsx
  src/components/events/week/customevent.tsx
  src/components/ui/calendar.tsx
Labels: ready for review

#1138 J1munoz/app buttons
  src/app/programs/create/page.tsx
  src/app/programs/das/page.tsx
  src/app/programs/forge/page.tsx
  src/app/programs/spark/page.tsx
  src/components/events/calendarcall.tsx
  src/components/events/upcomingevents/upcomingevents.tsx
  src/components/home/currentopportunities.tsx
  src/components/home/opportunitiescard.tsx
  src/components/programs/bitbyte/join.tsx
  src/components/programs/joinus.tsx
  src/data/opportunities.ts
  src/utils/applications/applicationstatus.ts
  src/utils/applications/currentapplications.ts
Labels: ready for review

#1152 Fix calendar popup
  package-lock.json
  src/components/events/month/calendareventpopover.tsx
  src/components/events/week/customevent.tsx
  src/components/hacks/hackathons.tsx
  src/components/ui/dialog.tsx
  src/components/ui/popover.tsx
Labels: approved 1x

#1142 Yos shimono/photo gallery
  public/forgepage/photogallery/image1.webp
  public/forgepage/photogallery/image2.webp
  public/forgepage/photogallery/image3.webp
  public/forgepage/photogallery/image4.webp
  public/forgepage/photogallery/image5.webp
  public/sparkpage/photogallery/image1.webp
  public/sparkpage/photogallery/image2.webp
  public/sparkpage/photogallery/image3.webp
  public/sparkpage/photogallery/image4.webp
  public/sparkpage/photogallery/image5.webp
  src/app/programs/forge/page.tsx
  src/app/programs/spark/page.tsx
  src/components/programs/forge/photogallery.tsx
  src/components/programs/spark/photogallery.tsx
Labels: approved 1x

#1113 add animaitons
  package-lock.json
  src/components/hacks/hackathons.tsx
  src/components/hacks/whatweoffer.tsx
Labels: changes requested

#1135 implemented filter on week only
  package-lock.json
  package.json
  src/components/events/calendarcall.tsx
  src/components/events/month/calendareventpopover.tsx
  src/components/events/month/calendartop.tsx
  src/components/events/week/customtoolbar.tsx
  src/components/ui/calendar.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
Labels: ready for review

#1158 responsified week calendar
  src/components/events/week/customdayheader.tsx
  src/components/events/week/customevent.tsx
Labels: ready for review
