Repository acm-ucr/acm-atlas, pull requests merged in 2025-04, with the labels that each got.

#825 add exclamation marks
  src/app/page.tsx
Labels: ready for review

#831 Compressed Create and Spark Images
  public/Create/3d.webp
  public/Create/aag.webp
  public/Create/acmhydra.webp
  public/Create/asme.webp
  public/Create/bap.webp
  public/Create/csa.webp
  public/Create/cse.webp
  public/Create/cvdsa.webp
  public/Create/ewb.webp
  public/Create/hearts.webp
  public/Create/highlandergloves.webp
  public/Create/hlg.webp
  public/Create/hsp.webp
  public/Create/ieee.webp
  public/Create/iranianstudentassociation.webp
  public/Create/jmproduct.webp
  public/Create/pad.webp
  public/Create/quant.webp
  public/Create/rishi.webp
  public/Create/saf.webp
  public/Spark/aag.webp
  public/Spark/acmhydra.webp
  public/Spark/asme.webp
  public/Spark/bap.webp
  public/Spark/csa.webp
  public/Spark/cse.webp
  public/Spark/cvdsa.webp
  public/Spark/ewb.webp
  public/Spark/hearts.webp
  public/Spark/highlandergloves.webp
  public/Spark/hlg.webp
  public/Spark/hsp.webp
  public/Spark/ieee.webp
  public/Spark/iranianstudentassociation.webp
  public/Spark/jmproduct.webp
  public/Spark/pad.webp
  public/Spark/quant.webp
  public/Spark/rishi.webp
  public/Spark/saf.webp
Labels: ready for review

#839 p tag DAS
  src/app/programs/das/page.tsx
  src/components/programs/das.tsx
Labels: ready for review

#838 p tag page not found
  src/app/not-found.tsx
Labels: ready for review

#845 Added P tag to Create page
  src/app/programs/create/page.tsx
  src/components/programs/create/header.tsx
Labels: ready for review

#837 Programs header
  src/app/programs/page.tsx
Labels: ready for review

#843 home page tite
  src/app/page.tsx
Labels: ready for review

#841 Andres Lopez / Added p-tag on the SPARK page
  src/app/programs/spark/page.tsx
  src/components/programs/spark/title.tsx
Labels: ready for review

#849 created p tag for FORGE
  src/app/programs/forge/page.tsx
  src/components/programs/forge/header.tsx
Labels: ready for review

#840 programs page text
  src/app/programs/page.tsx
Labels: ready for review

#847 BIT/BYTE Page
  src/app/programs/bitbyte/page.tsx
  src/components/programs/bitbyte/header.tsx
Labels: ready for review

#861 renamed to Header
  src/app/board/page.tsx
  src/components/board/Header.tsx
Labels: ready for review

#869 Added View All Link
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/home/viewalllink.tsx
Labels: approved 1x

#867 footer
  src/app/layout.tsx
  src/components/footer.tsx
Labels: approved 1x

#868 Added ACM Image to Home
  public/Home/ACM_Keys.svg
  src/components/home/header.tsx
Labels: approved 1x

#890 changed output to standalone in next.config.js
  next.config.js
Labels: ready for review

#891 made programs in navbar clickable and send user to programs page
  src/components/navigation.tsx
Labels: ready for review

#866 Andres Lopez / "See More" Link Tag on Home
  src/app/page.tsx
  src/components/home/seemorelink.tsx
Labels: approved 1x

#871 Finished the Web Dev component
  public/acmspark.svg
  src/app/globals.css
  src/app/programs/page.tsx
  src/components/programs/whatweoffer.tsx
  src/components/programs/whatweoffers.tsx
  src/data/whatweoffer.ts
Labels: approved 1x

#889 p-tag for the Upcoming Events title on the home page
  src/app/page.tsx
  src/components/home/UpcomingEvents.tsx
Labels: approved 1x

#850 created current opportunities text for home page
  src/components/home/currentopportunities.tsx
Labels: ready for review

#896 Sarbesh1234/featured projects
  src/app/page.tsx
  src/components/home/featuredprojects.tsx
Labels: approved 1x

#898 J1munoz/nav bar mobile
  src/components/navigation.tsx
  src/data/navigations.ts
Labels: approved 1x

#900 footer component
  src/components/footer.tsx
Labels: approved 1x

#895 starlight buttons
  src/app/hacks/starlight/page.tsx
  src/components/hacks/starlight/starlightbuttons.tsx
Labels: approved 1x

#902 boardCard completed
  src/app/board/page.tsx
  src/app/globals.css
  src/components/board/boardcard.tsx
  src/components/board/boardcards.tsx
  src/data/board.ts
Labels: approved 1x

#903 Added Project Card
  src/app/programs/spark/page.tsx
  src/components/programs/spark/projectgrid.tsx
  src/components/projectcard.tsx
  src/data/projects/spark.ts
Labels: approved 1x

#905 Join Now text, button, and image. Has a placeholder at the moment. On…
  public/DAS_2.jpg
  public/create1.jpg
  public/forge_1.jpg
  public/spark_1.jpg
  src/app/programs/bitbyte/page.tsx
  src/app/programs/create/page.tsx
  src/app/programs/das/page.tsx
  src/app/programs/forge/page.tsx
  src/app/programs/spark/page.tsx
  src/components/programs/join-now-bitbyte.tsx
  src/components/programs/join-now.tsx
Labels: ready for review

#897 implemented go back home button
  src/app/not-found.tsx
Labels: changes requested

#912 Andres Lopez / Our Vision Grid
  public/about/ourvision1.webp
  public/about/ourvision2.webp
  public/about/ourvision3.webp
  public/about/ourvision4.webp
  src/app/about/page.tsx
  src/components/about/aboutus.tsx
  src/components/about/ourvision.tsx
Labels: ready for review

#908 Project Card Home
  public/create/acm.webp
  public/create/nsu.webp
  public/create/witl.webp
  public/forge/blank.webp
  public/forge/drone.webp
  public/forge/wzchess.webp
  public/spark/aviatr.webp
  public/spark/pad.webp
  public/spark/saf.webp
  src/components/home/featuredprojects.tsx
  src/components/home/projectcard.tsx
Labels: approved 1x

#899 add path
  src/app/page.tsx
  src/components/home/landing.tsx
  src/components/navigation.tsx
  src/data/navigations.ts
Labels: changes requested

#915 Event Card
  public/Event/at.svg
  public/Event/barchart.svg
  public/Event/cursor.svg
  public/Event/gear.svg
  public/Event/message.svg
  public/Event/tags.svg
  src/app/globals.css
  src/components/events/eventcard.tsx
Labels: approved 1x

#910 Added stats grid to homepage
  public/DAS_2.webp
  public/create1.webp
  public/forge_1.webp
  public/spark_1.webp
  src/app/page.tsx
  src/app/programs/das/page.tsx
  src/app/programs/forge/page.tsx
  src/app/programs/spark/page.tsx
  src/components/home/statsgrid.tsx
Labels: approved 1x

#939 finished headers for all programs
  public/DAS_2.webp
  public/create1.webp
  public/ellipses/blueEllipse.svg
  public/ellipses/grayEllipse.svg
  public/ellipses/greenEllipse.svg
  public/ellipses/purpleEllipse.svg
  public/ellipses/yellowEllipse.svg
  public/events/at.svg
  public/events/barchart.svg
  public/events/cursor.svg
  public/events/gear.svg
  public/events/message.svg
  public/events/tags.svg
  public/forge_1.webp
  public/logos/bitbyte.svg
  public/logos/create.svg
  public/logos/das.svg
  public/logos/forge.svg
  public/logos/spark.svg
  public/spark_1.webp
  src/app/programs/bitbyte/page.tsx
  src/app/programs/create/page.tsx
  src/app/programs/das/page.tsx
  src/app/programs/forge/page.tsx
  src/app/programs/spark/page.tsx
  src/components/programs/bitbyte/header.tsx
  src/components/programs/create/header.tsx
  src/components/programs/das/header.tsx
  src/components/programs/forge/header.tsx
  src/components/programs/programheader.tsx
  src/components/programs/spark/header.tsx
  src/data/hackathons.ts
  src/data/whatweoffer.ts
Labels: ready for review

#930 Gmatt20/do it grid
  public/about/whywedoit1.webp
  public/about/whywedoit2.webp
  public/about/whywedoit3.webp
  public/about/whywedoit4.webp
  src/app/about/page.tsx
  src/components/about/whywedoit.tsx
  src/components/programs/das.tsx
Labels: approved 1x

#952 Yos shimono/current opportunities
  public/Home/CurrentOpportunities/bitbyte.svg
  public/Home/CurrentOpportunities/create.svg
  public/Home/CurrentOpportunities/das.svg
  public/Home/CurrentOpportunities/forge.svg
  public/Home/CurrentOpportunities/spark.svg
  src/app/page.tsx
  src/components/home/currentopportunities.tsx
  src/components/home/opportunitiescard.tsx
  src/data/opportunities.ts
Labels: approved 1x

#949 404 page
  public/404/404_Keys.webp
  src/app/globals.css
  src/app/not-found.tsx
  tsconfig.json
Labels: ready for review
