Repository acm-ucr/acm-atlas, pull requests merged in 2025-05, with the labels that each got.

#965 Sidebar
  public/board/create/kaylie.webp
  public/board/create/shirley.webp
  public/board/das/khushi.webp
  public/board/forge/marcus.webp
  public/board/spark/aldrie.webp
  public/board/spark/alton.webp
  public/board/spark/arielle.webp
  public/board/spark/brandon.webp
  public/board/spark/charleen.webp
  public/board/spark/cole.webp
  public/board/spark/dean.webp
  public/board/spark/hannah.webp
  public/board/spark/john.webp
  public/board/spark/kevin.webp
  public/board/spark/mailyn.webp
  public/board/spark/nidheesh.webp
  public/board/spark/quin.webp
  public/board/spark/stanley.webp
  public/board/spark/sweden.webp
  public/board/spark/tingxuan.webp
  public/board/spark/wesley.webp
  src/app/board/page.tsx
  src/components/board/card.tsx
  src/components/board/cards.tsx
  src/components/board/sidebar.tsx
  src/data/board.ts
  src/data/logos.ts
Labels: ready for review

#931 what we do grid
  public/about/whatwedo1.webp
  public/about/whatwedo2.webp
  public/about/whatwedo3.webp
  public/about/whatwedo4.webp
  src/app/about/page.tsx
  src/components/about/ourvision.tsx
  src/components/about/whatwedo.tsx
  src/components/about/whywedoit.tsx
Labels: changes requested

#957 accordian for FAQ
  package-lock.json
  package.json
  src/app/programs/bitbyte/page.tsx
  src/app/programs/create/page.tsx
  src/app/programs/das/page.tsx
  src/app/programs/forge/page.tsx
  src/app/programs/spark/page.tsx
  src/components/programs/bitbyte/faq.tsx
  src/components/programs/create/faq.tsx
  src/components/programs/das/faq.tsx
  src/components/programs/forge/faq.tsx
  src/components/programs/spark/faq.tsx
  src/components/ui/accordion.tsx
Labels: approved 1x

#967 hackathon data
  package-lock.json
  package.json
  src/app/hacks/[hackathon]/page.tsx
  src/app/not-found.tsx
  src/components/hacks/hack.tsx
  src/components/home/currentopportunities.tsx
  src/components/statitem.tsx
  src/data/hackathons.ts
Labels: approved 1x

#970 added what we offer
  src/components/programs/whatweoffer.tsx
  src/data/whatweoffer.ts
Labels: changes requested

#1003 Fixed Techstack name
  src/app/programs/create/page.tsx
  src/app/programs/das/page.tsx
  src/app/programs/forge/page.tsx
  src/app/programs/spark/page.tsx
  src/data/techstacks/create.ts
  src/data/techstacks/das.ts
  src/data/techstacks/forge.ts
  src/data/techstacks/spark.ts
Labels: ready for review

#951 Amir/landing
  package-lock.json
  public/home/acmLogo.svg
  src/components/home/currentopportunities.tsx
  src/components/home/landing.tsx
  src/components/home/statsgrid.tsx
  src/components/join/faq.tsx
  src/components/statitem.tsx
Labels: ready for review

#950 Aurora Landing page
  package-lock.json
  public/logos/aurora.svg
  public/logos/aurorastar.webp
  src/app/hacks/aurora/page.tsx
  src/components/hacks/aurora/aurorabuttons.tsx
  src/components/hacks/aurora/header.tsx
  src/components/hacks/aurora/stats.tsx
  src/components/programs/programheader.tsx
  tailwind.config.ts
Labels: ready for review

#994 Andres Lopez / Hack.tsx Part 1
  src/app/hacks/[hackathon]/page.tsx
  src/components/hacks/hack.tsx
  src/data/board.ts
  src/data/hackathons.ts
  tailwind.config.ts
Labels: approved 1x

#1011 image hover
  src/app/globals.css
  src/components/about/ourvision.tsx
  src/components/about/whatwedo.tsx
  src/components/about/whywedoit.tsx
Labels: approved 1x

#1018 mobile footer
  src/components/footer.tsx
Labels: approved 1x

#1019 Andres Lopez / Mobile Responsive Join Now
  src/components/programs/bitbyte/join.tsx
  src/components/programs/carousel.tsx
  src/components/programs/joinus.tsx
  src/components/programs/programheader.tsx
Labels: ready for review

#1021 Program Header Responsiveness
  src/components/programs/programheader.tsx
Labels: approved 1x

#1006 Mobile Response for What We Offer
  src/components/programs/whatweoffer.tsx
  src/components/programs/whatweoffers.tsx
Labels: approved 1x

#995 mobile responsiveness: featured projects
  src/components/home/featuredprojects.tsx
  src/components/home/projectcard.tsx
Labels: ready for review

#1010 create what we do
  public/create/whatwedo1.webp
  public/create/whatwedo2.webp
  src/app/programs/create/page.tsx
  src/components/programs/create/whatwedo.tsx
  tailwind.config.ts
Labels: ready for review

#1026 gmatt20/green-bitbyte
  src/components/programs/bitbyte/join.tsx
Labels: approved 1x

#1007 Andres Lopez / Used In Aurora Component
  src/app/hacks/aurora/page.tsx
  src/components/hacks/aurora/usedin.tsx
  src/data/hackathons.ts
Labels: ready for review

#1028 Jschu051/week6 dadgridcontent
  public/das/das2.webp
  src/app/programs/das/page.tsx
  src/components/programs/das/whatwedo.tsx
  src/components/programs/whatweoffers.tsx
Labels: approved 1x

#1005 forge what we do
  public/forge/image1.webp
  public/forge/image2.webp
  public/forge/image3.webp
  public/forge/image4.webp
  src/app/programs/forge/page.tsx
  src/components/programs/forge/whatwedo.tsx
  tailwind.config.ts
Labels: approved 1x

#1014 What we do
  public/spark/left.webp
  public/spark/right.webp
  src/app/programs/spark/page.tsx
  src/components/home/landing.tsx
  src/components/programs/spark/whatwedo.tsx
Labels: approved 1x

#1015 Features
  src/app/hacks/aurora/page.tsx
  src/components/hacks/aurora/features.tsx
  src/data/hacks/features.ts
Labels: approved 1x

#1017 programs project card
  src/components/programs/projectcard.tsx
  src/components/programs/spark/projectgrid.tsx
Labels: approved 1x

#1036 Andres Lopez / Animated Current Opportunity Card Component
  package-lock.json
  package.json
  src/components/home/opportunitiescard.tsx
Labels: approved 1x

#993 Sarbesh1234/hackpacks
  src/app/hacks/hackpacks/page.tsx
  src/components/footer.tsx
  src/components/hacks/hackpacks/card.tsx
  src/components/hacks/hackpacks/cards.tsx
  src/data/hackpacks.tsx
  tailwind.config.ts
Labels: approved 1x

#1044 animated what we offer component
  next.config.js
  package-lock.json
  package.json
  src/components/hacks/hacks.tsx
  src/components/hacks/whatweoffer.tsx
Labels: approved 1x

#966 Pagination & Search Bar
  package-lock.json
  package.json
  src/app/programs/create/page.tsx
  src/app/programs/spark/page.tsx
  src/components/about/whatwedo.tsx
  src/components/board/sidebar.tsx
  src/components/home/currentopportunities.tsx
  src/components/programs/pagination.tsx
  src/components/programs/projectcard.tsx
  src/components/programs/projectgrid.tsx
  src/components/programs/projects.tsx
  src/components/programs/search.tsx
  src/components/programs/spark/projectgrid.tsx
  src/components/ui/button.tsx
  src/components/ui/pagination.tsx
  src/data/projects/create.ts
  src/data/projects/spark.ts
Labels: approved 1x

#1025 Added orders to blurb and photo grid
  package-lock.json
  src/components/about/ourvision.tsx
  src/components/about/whatwedo.tsx
  src/components/about/whywedoit.tsx
Labels: ready for review

#1048 program animations
  src/components/programs/whatweoffer.tsx
Labels: ready for review

#1047 Added orders to the Join now and Apply Here buttons, they now appear after the blurb
  package-lock.json
  src/components/footer.tsx
  src/components/programs/bitbyte/join.tsx
Labels: approved 1x

#1055 added animations outside
  src/components/programs/programheader.tsx
Labels: ready for review

#1059 calendar
  package-lock.json
  package.json
  public/board/forge/justin.webp
  src/app/events/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/events/calendarday.tsx
  src/components/events/calendareventpopover.tsx
  src/components/events/calendartop.tsx
  src/components/events/card.tsx
  src/components/events/cards.tsx
  src/components/events/eventcard.tsx
  src/components/events/header.tsx
  src/components/events/upcomingevents.tsx
  src/components/footer.tsx
  src/components/home/opportunitiescard.tsx
  src/components/home/seemore.tsx
  src/components/home/seemorelink.tsx
  src/components/home/upcoming.tsx
  src/components/programs/create/whatwedo.tsx
  src/components/programs/programheader.tsx
  src/components/programs/spark/whatwedo.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/dialog.tsx
  src/components/ui/popover.tsx
  src/data/board.ts
  src/data/opportunities.ts
  tailwind.config.ts
Labels: ready for review

#1027 Carousel Photos
  public/hacks/citrushack/citrushack1.webp
  public/hacks/citrushack/citrushack2.webp
  public/hacks/citrushack/citrushack3.webp
  public/hacks/citrushack/citrushack4.webp
  public/hacks/citrushack/citrushack5.webp
  public/hacks/citrushack/citrushack6.webp
  public/hacks/designverse/designverse1.webp
  public/hacks/designverse/designverse10.webp
  public/hacks/designverse/designverse2.webp
  public/hacks/designverse/designverse3.webp
  public/hacks/designverse/designverse4.webp
  public/hacks/designverse/designverse5.webp
  public/hacks/designverse/designverse6.webp
  public/hacks/designverse/designverse7.webp
  public/hacks/designverse/designverse8.webp
  public/hacks/designverse/designverse9.webp
  public/hacks/rosehack/rosehack1.webp
  public/hacks/rosehack/rosehack2.webp
  public/hacks/rosehack/rosehack3.webp
  public/hacks/rosehack/rosehack4.webp
  src/app/hacks/[hackathon]/page.tsx
  src/components/hacks/carousel.tsx
  src/components/hacks/hack.tsx
  src/data/hackathons.ts
  src/data/hacks/citrushackimages.ts
  src/data/hacks/designverseimages.ts
  src/data/hacks/rosehackimages.ts
Labels: approved 1x

#1045 New branch for projects animations
  src/components/home/featuredprojects.tsx
  src/components/home/projectcard.tsx
Labels: ready for review

#1051 Animate Join Us
  src/components/programs/joinus.tsx
Labels: approved 1x

#1053 LANDING TITLE ANIMATION
  src/components/home/landing.tsx
Labels: approved 1x

#1050 Mob NavBar Animation
  package-lock.json
  src/components/navigation.tsx
Labels: approved 1x

#1083 Debugged Animations
  src/components/programs/whatweoffer.tsx
Labels: approved 1x

#1081 gmatt20/hackpacks-mr
  src/components/hacks/hackpacks/cards.tsx
Labels: changes requested

#1085 fetched total commits in Aurora repo
  src/components/hacks/aurora/stats.tsx
Labels: ready for review

#1114 add border
  src/components/navigation.tsx
Labels: ready for review

#1119 Stars
  src/components/hacks/aurora/stats.tsx
Labels: approved 1x

#1122 # Of Closed Issues Aurora
  src/components/hacks/aurora/stats.tsx
Labels: approved 1x

#1115 added data
  src/app/programs/create/page.tsx
  src/app/programs/das/page.tsx
  src/app/programs/forge/page.tsx
  src/app/programs/spark/page.tsx
  src/components/programs/create/stats.tsx
  src/components/programs/das/stats.tsx
  src/components/programs/forge/stats.tsx
  src/components/programs/spark/stats.tsx
Labels: ready for review

#1056 Animated cards
  package-lock.json
  src/app/board/page.tsx
  src/components/board/cards.tsx
  src/data/logos.ts
Labels: approved 1x

#1079 Andres Lopez / Aurora Contributor API
  src/components/hacks/aurora/stats.tsx
Labels: approved 1x

#1129 added shadow
  public/logos/bitbyte.svg
  public/logos/create.svg
  public/logos/das.svg
  public/logos/forge.svg
  public/logos/spark.svg
  src/components/hacks/hackathons.tsx
  src/components/home/currentopportunities.tsx
  src/components/programs/whatweoffer.tsx
Labels: approved 1x

#1126 FOOTER ANIMATIONS
  src/components/footer.tsx
Labels: approved 1x

#1054 added animation
  src/components/home/landing.tsx
Labels: approved 1x

#1120 Added shadows to icons
  src/components/about/whatwedo.tsx
Labels: changes requested

#1080 API Call Closed PRs
  src/components/hacks/aurora/stats.tsx
Labels: approved 1x

#1049 navbar animation
  src/components/footer.tsx
  src/components/navigation.tsx
Labels: changes requested

#1133 changes
  src/app/not-found.tsx
  src/components/hacks/hackathons.tsx
  src/components/hacks/whatweoffer.tsx
  src/components/join/instagram.tsx
  src/components/programs/whatweoffer.tsx
  src/components/programs/whatweoffers.tsx
Labels: ready for review
